---

- name: install base packages
  yum: pkg="{{ item }}" state="installed"
  with_items:
    - "{{ base_pkgs }}"

- name: ansible root key
  authorized_key: user=root key="{{ item }}"
  with_file:
    - ansible-id-rsa.pub
  tags:
    - base

- name: reserve the gid 1000 for the demo user
  group: name=demouser gid=1001 

- name: reserve the uid 1000 for the demo user
  user: name=demouser uid=1001

- name: Add demouser to the sudoers list
  copy: src=demouser.conf dest=/etc/sudoers.d/demouser owner=root group=root mode=0644
