---

- name: install base packages
  with_items:
    - "{{ base_pkgs }}"

- name: ansible root key
  authorized_key: user=root key="{{ item }}"
  with_file:
    - ansible-id-rsa.pub
  tags:
    - base

- name: copy the hosts template around until we have proper DNS
  template: src=etc.hosts.j2 dest=/etc/hosts

- name: iptables
  template: src={{ item }} dest=/etc/sysconfig/iptables
  with_first_found:
    - ../templates/iptables/iptables.{{ ansible_fqdn }} 
    - ../templates/iptables/iptables.{{ host_group }}
    - ../templates/iptables/iptables
  notify: 
    - restart iptables
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version <= 7
  tags:
    - base
    - iptables

- name: reserve the gid 1000 for the demo user
  group: name=demouser gid=1000 

- name: reserve the uid 1000 for the demo user
  user: name=demouser uid=1000

- name: Add bstinson to the sudoers list
  copy: src=demouser.conf dest=/etc/sudoers.d/demouser owner=root group=root mode=0644
